# Generated by Django 3.1 on 2021-05-19 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_remove_answer_votes'),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votecast',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_casts', to='answers.answer'),
        ),
    ]
