# Generated by Django 3.1 on 2021-05-19 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20210519_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votecast',
            name='vote_balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_casts', to='votes.votebalance'),
        ),
    ]
