# Generated by Django 3.1 on 2021-05-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_deq_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=640)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
            ],
        ),
    ]
