# Generated by Django 3.1 on 2021-05-19 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deq_balance',
        ),
    ]
