# Generated by Django 3.1 on 2021-05-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_deq_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=12)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
