# Generated by Django 3.1 on 2021-05-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alphacode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alphacode',
            name='code',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
    ]
