# Generated by Django 3.1 on 2021-06-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210530_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('use_count', models.IntegerField(default=1)),
                ('used', models.IntegerField(default=0)),
                ('endowment', models.DecimalField(decimal_places=18, default=0.0, max_digits=29)),
            ],
        ),
    ]
