# Generated by Django 3.1 on 2021-06-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_signupcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlphaCode',
        ),
    ]
