# Generated by Django 3.1 on 2021-06-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_alphacode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupcode',
            name='code',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
    ]
