# Generated by Django 3.1 on 2021-06-30 04:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210625_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordcode',
            name='expiration_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 4, 1, 25, 784744, tzinfo=utc)),
        ),
    ]
