# Generated by Django 3.1 on 2021-07-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210701_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordcode',
            name='expiration_datetime',
            field=models.DateTimeField(),
        ),
    ]
