# Generated by Django 3.1 on 2021-08-28 17:30

import backend.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210701_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eth_address',
            field=models.CharField(blank=True, default='', max_length=64, validators=[backend.users.models.validate_eth_address]),
        ),
        migrations.AddField(
            model_name='user',
            name='web_link',
            field=models.URLField(blank=True, default='', max_length=400),
        ),
    ]
