# Generated by Django 3.1 on 2021-06-30 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.JSONField(default=dict)),
                ('category', models.CharField(choices=[('email', 'Email')], max_length=64)),
                ('delivery_method', models.CharField(choices=[('email', 'Email')], max_length=64)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('new', 'Initially created'), ('proccessing', 'In process'), ('failed', 'Failed'), ('sent', 'Sent')], default='new', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
