# Generated by Django 3.1 on 2021-08-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210630_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('answer_created', 'Answer Created'), ('out_of_band', 'Out of band'), ('reset_password', 'Reset password')], max_length=64),
        ),
    ]
