# Generated by Django 3.1 on 2021-05-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_prompt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='bounty',
            field=models.IntegerField(default=0),
        ),
    ]
