# Generated by Django 3.1 on 2021-05-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0003_prompt_bounty'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='added_bounty',
            field=models.IntegerField(default=0),
        ),
    ]
