# Generated by Django 3.1 on 2021-05-19 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0004_prompt_added_bounty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='added_bounty',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='bounty',
        ),
    ]
