# Generated by Django 3.1 on 2021-05-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0005_auto_20210519_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='status',
            field=models.CharField(choices=[('active', 'Active for answers'), ('closing', 'Prompt is closed for answers and caclulating distribution'), ('closed', 'Prompt is closed and bounties are distributed')], default='active', max_length=64),
        ),
    ]
