# Generated by Django 3.1 on 2021-06-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0006_prompt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='title',
            field=models.CharField(max_length=210),
        ),
    ]
