# Generated by Django 3.1 on 2021-06-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0007_auto_20210604_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='askers_cut',
            field=models.FloatField(default=0.0),
        ),
    ]
