# Generated by Django 3.1 on 2021-06-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0008_prompt_askers_cut'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='hidden_code',
            field=models.CharField(default='', max_length=32),
        ),
    ]
