# Generated by Django 3.1 on 2021-06-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0009_prompt_hidden_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='hidden_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
