# Generated by Django 3.1 on 2021-07-01 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prompts', '0010_auto_20210625_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watchers', to='prompts.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watching', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
