# Generated by Django 3.1 on 2021-05-19 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeqTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=18, default=0.0, max_digits=29)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('from_answer', 'From upvoted answer'), ('from_prompt_added_bounty', 'From added bounty'), ('to_prompt_bounty', 'To create a prompt bounty')], max_length=64)),
                ('other_pk', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
