# Generated by Django 3.1 on 2021-05-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20210519_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deqtransaction',
            name='category',
            field=models.CharField(choices=[('from_answer', 'From upvoted answer'), ('from_prompt_added_bounty', 'From added bounty'), ('from_source', 'From source database'), ('from_expired_prompt', 'Prompt expired with no answers'), ('to_prompt_bounty', 'To create a prompt bounty')], max_length=64),
        ),
    ]
