# Generated by Django 3.1 on 2021-05-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20210522_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='deqtransaction',
            name='status',
            field=models.CharField(choices=[('new', 'Initially created'), ('proccessing', 'In process'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled')], default='fulfilled', max_length=64),
        ),
        migrations.AlterField(
            model_name='deqtransaction',
            name='category',
            field=models.CharField(choices=[('from_answer', 'From upvoted answer'), ('from_prompt_added_bounty', 'From added bounty'), ('from_source', 'From source database'), ('from_expired_prompt', 'Prompt expired with no answers'), ('to_eth', 'DEQ cashed out to ETH'), ('to_prompt_bounty', 'To create a prompt bounty')], max_length=64),
        ),
        migrations.AlterField(
            model_name='deqtransaction',
            name='other_pk',
            field=models.IntegerField(null=True),
        ),
    ]
