# Generated by Django 3.1 on 2021-05-27 05:00

from django.db import migrations


def forwards_func(apps, schema_editor):
    DeqTransaction = apps.get_model('transactions', 'DeqTransaction')
    Answer = apps.get_model('answers', 'Answer')
    deq_transactions = DeqTransaction.objects.all()
    for deq_transaction in deq_transactions:
        if deq_transaction.category == 'from_answer':
            answer = Answer.objects.get(pk=deq_transaction.other_pk)
            deq_transaction.extra_info = {'answer': answer.pk, 'prompt': answer.prompt.pk}
        elif deq_transaction.category in ['from_expired_prompt', 'to_prompt_bounty', 'from_prompt_added_bounty']:
            deq_transaction.extra_info = {'prompt': deq_transaction.other_pk}
        deq_transaction.save(update_fields=['extra_info'])


def reverse_func(apps, schema_editor):
    DeqTransaction = apps.get_model('transactions', 'DeqTransaction')
    DeqTransaction.objects.all().update(extra_info={})


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20210527_0453'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
