# Generated by Django 3.1 on 2021-05-27 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20210527_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deqtransaction',
            name='other_pk',
        ),
    ]
