# Generated by Django 3.1 on 2021-06-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_deqtransaction_other_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deqtransaction',
            name='category',
            field=models.CharField(choices=[('from_answer', 'From upvoted answer'), ('from_prompt_added_bounty', 'From added bounty'), ('from_source', 'From source database'), ('from_expired_prompt', 'Prompt expired with no answers'), ('increase_prompt_bounty', 'Increase a prompt bounty'), ('to_eth', 'DEQ cashed out to ETH'), ('to_usd', 'DEQ cashed out to USD'), ('to_prompt_bounty', 'To create a prompt bounty')], max_length=64),
        ),
    ]
