# Generated by Django 3.1 on 2021-05-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(default=1),
        ),
    ]
