# Generated by Django 3.1 on 2021-05-19 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20210518_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='votes',
        ),
    ]
